spring:
  datasource:
    password: 156437734
    url: jdbc:mysql://47.98.210.55:3306/atguigu?serverTimezone=GMT%2B8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
  thymeleaf:
    cache: false
server:
  port: 8080




